_target_: lightning.pytorch.Trainer
max_epochs: 1
callbacks: null
# devices: ${device_count:} 
devices: 1 #(AT)
log_every_n_steps: 1
limit_train_batches: 1.0
limit_val_batches: 1.0
# val_check_interval: ${eval:${trainer.accumulate_grad_batches} * ${div_up:${task.val_check_interval}, ${eval:${trainer.devices} * ${trainer.num_nodes}}}}
val_check_interval: 0.5
gradient_clip_val: 1.0
precision: "16-mixed"
num_sanity_val_steps: 0
num_nodes: 1
accumulate_grad_batches: ${div_up:${task.global_batch_size}, ${eval:${trainer.devices} * ${dataset.batch_size_per_device} * ${trainer.num_nodes}}}
#(AT)
# strategy:
#    _target_: lightning.pytorch.strategies.DDPStrategy